name: WormGPT Kaggle Miner

on:
  workflow_dispatch: # Cho phép bấm nút chạy tay
  schedule:
    - cron: '0 */6 * * *' # Tự động chạy lại sau mỗi 6 tiếng (để bào liên tục)

jobs:
  mining:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Cài đặt Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Cài đặt thư viện cần thiết
      run: |
        pip install playwright nest_asyncio
        playwright install chromium

    - name: Chạy Bot Kaggle
      run: python 1.py
